### ISSUE TITLE
Static file paths

### ISSUE THREAD

**Issue by aaronr8684** [pi3d/pi3d_demos#11]
both the "FONT_FILE" and "shader" variables use static paths causing errors if the script path isn't the default. It seems like a relative path based on the script running directory would be more robust.

**Comment by paddywwoof** [comment]
Hi, I agree that generally that would be better. I'm not sure which demo you're looking at but the one that causes issues is PictureFrame.py This has been written up very comprehensively by @sapnho on his blog and the recommended route to get it to run automatically on the RPi4 uses xinit... from the command line. That route seems to require absolute paths to function predictably so I changed the demo to reflect that.

If it's a different demo let me know. Happy to look at improvements to the code base.

Paddy
