### ISSUE TITLE
Ghost Image

### ISSUE THREAD

**Issue by NeuroDawg** [pi3d/pi3d_demos#12]
I discovered PictureFrame.py via thedigitalpictureframe.com and have been using it for the past week. I have been noticing that frequently I will see a ghost image after the transition. For example, a.jpg fades into b.jpg and I can still see, faintly, a.jpg. It appears that the transition doesn't get all the way to b.jpg only, stopping one or two blurs away from a.jpg completely disappearing. Have you noticed this?

Second question, is there a way to change from the "blend_new" shader and use a different shader. I've tried replacing "blend_new" in line 242 to a different shader, but that doesn't display images.

Thanks for a fantastic program!

**Comment by paddywwoof** [comment]
Hi, happy christmas (nearly). Yes, I have noticed that non-linear fading in the past and meant to investigate and fix it. I think it's something to do with the rounding error of floats in the shader language (GLSL) which is set to mediump as that's all that's supported on some architectures (mali gpu). I will look a bit harder in the new year and fix it.

At the moment the alternative shaders are rather inflexibly just commented out in the fragment shader. That's in ``pi3d_demos/shaders/blend_new.fs`` you will see two alternatives commented out.
```
  // simple fade //////////////////////////////////////////////////////
  gl_FragColor = mix(texb, texf, a);

  // burn /////////////////////////////////////////////////////////////
  //float y = 1.0 - smoothstep(a, a * 1.2, length(texf.rgb) * 0.577 + 0.01);
  //gl_FragColor = mix(texb, texf * y, step(1.0, y));

  // bump /////////////////////////////////////////////////////////////
  //vec4 light = vec4(0.577, 0.577, 0.577, 1.0);
  //float ffact = dot(light, texf);
  //gl_FragColor = mix(texb * (1.0 + a * (ffact - 1.0)), texf, clamp(2.0 * a - 1.0, 0.0, 1.0));
```
You can mess around with these to see what they do. mix() is a simple linear interpolation between the first two arguments (foreground and bkground pixel values). burn switches between fg and bg accoring to the brightness of the fg multiplied by the fade factor (a). bump mixes fg and bg according to the light hitting the fg texture interpreted as 4D surface. The possibilities are endless - let me know if you find any really cool effects... or if you get stuck and want some help. Make a copy of blend_new.fs before you change anything!
