### ISSUE TITLE
PictureFrame2020.py: MQTT quit command not working with Keyboard=False

### ISSUE THREAD

**Issue by mortara** [pi3d/pi3d_demos#17]
Hi,

if the Keyboard input is disabled in PictureFrame2020, a MQTT frame/quit will have no effect because the quit variable is never evaluated:

`if config.KEYBOARD:
    k = kbd.read()
    if k != -1:
      nexttm = time.time() - 86400.0
    if k==27 or quit: #ESC
      break
    if k==ord(' '):
      paused = not paused
    if k==ord('s'): # go back a picture
      next_pic_num -= 2
      if next_pic_num < -1:
        next_pic_num = -1`

**Comment by paddywwoof** [comment]
Thanks for that. Being able to quit with MQTT is exactly what you need if the keyboard is disabled. I've fixed that and pushed new version to this repo master branch.

Paddy
