### ISSUE TITLE
I stuck on "import demo"

### ISSUE THREAD

**Issue by imjackicle** [pi3d/pi3d_demos#3]
How can I install 'demo'?

`$ pip install demo
Collecting demo
  Could not find a version that satisfies the requirement demo (from versions: )
No matching distribution found for demo`

**Comment by paddywwoof** [comment]
Hi @imjackicle, pip only works for installing python modules and this repository is just a big jumble of examples for people to play with. If you have installed pi3d (which is a module and can be done with pip) then the best thing is to 'just' download the zip version of this repo using the 'clone or download' button then choose zip. This is the link you get https://github.com/pi3d/pi3d_demos/archive/master.zip

I will add a bit of explanation at the top of the ReadMe to this effect!
