### ISSUE TITLE
Raspberry Pi Touchscreen ends PictureFrame?

### ISSUE THREAD

**Issue by draycon88** [pi3d/pi3d_demos#30]
Hi,

is it even possible to end PictureFrame Slideshows without keyboard but with only a single touch on the touchdisplay from the Raspberry Pi ? Without Keyboard attached there is no possibility or I'm dumb, I dont' know.

Thanks a lot!

**Comment by paddywwoof** [comment]
Hi, Yes that question was asked recently [here](https://github.com/tipam/pi3d/issues/247) so have a look over that but please get back to me with any issues, or if it works fine, and I will add some more info to the documentation to help others.

The main thing is that you need to have your RPi set up so the touchscreen works to give a mouse input without the picture frame running, then add the Mouse code to pi3d on the simplest demo (Minimal.py), then add code to PictureFrame2000.py. I can conceive various problems you might have but without your setup it's hard to be more specific.

Let me know how you get on
Paddy
