### ISSUE TITLE
How to exit from PictureFrame.py  one time that I launched it?

### ISSUE THREAD

**Issue by matteoraggi** [pi3d/pi3d_demos#6]
Hi, from raspbian stretch, I launch this from the GUI and it works perfect! 
But then to exit from it the only way is to plug off the electricity to the raspberry.
Is there a more intelligent way to exit from python3 PictureFrame.py one time launched?

**Comment by paddywwoof** [comment]
Matteo, did you try ESC? What happened?

**Comment by matteoraggi** [comment]
Nothing it continue to play as if nothing new happened..

**Comment by paddywwoof** [comment]
Matteo, what happens with the other demos, for instance Minimal or Blur? I think they all use the same keyboard reading functionality. It might be worth putting a line into PictureFrame to make it break and see what happens (around line 112)
```
    pic_num = (pic_num + 1) % nFi # wraps to start
    if pic_num > 5:
        break
    if (pic_num % CHKNUM) == 0: # this will shuffle as well
```
