### ISSUE TITLE
No background alpha transparency when MESA driver is enabled

### ISSUE THREAD

**Issue by JeDy1111** [pi3d/pi3d_demos#9]
I run into a problem when the MESA driver is enabled. The alpha transparency on the background does not work.
I can easly be reproduced with the Raspberry_rain.py demo.
The background is dark when the MESA driver is enabled.

I have posted the issue on the Raspberry forum : https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=254790
It sounds like it is the way Pi3d is driving EGL.

Is there a way to solve the issue?

Thanks for your help.

**Comment by paddywwoof** [comment]
as of v2.33 this now works using pi3d.Display.create(... use_glx=True)

**Comment by JeDy1111** [comment]
Thanks Paddy!
